name: Build and test                                      
on:                                                       
  push:                                                     
    branches:                                               
      - master
jobs:                                                     
  build:                                                    
    runs-on: ubuntu-latest
    steps:
      - name: checkout code                                  
        uses: actions/checkout@v2                             
      - name: Set up JDK      
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: temurin                             
      - name: Test
        run: mvn test
      - name: Package
        run: mvn clean package

      - name: Log in to DockerHub Account
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.MY_SECRET_USERNAME }}
          password: ${{ secrets.MY_SECRET_PASSWORD }}

      - name: Build and a push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rohitballer/actiondemov1.0.0



